### ISSUE TITLE
Support old MacOS versions (Remove SwiftUI)

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/macos-wakatime#13]
To support MacOS `<13.0` we need to remove SwiftUI and use UIKit instead. Should we do this?

**Comment by livid** [comment]
If you did not use any SwiftUI 4 new features, stick with SwiftUI 3 features would make the app compatible with at least macOS 12.

**Comment by alanhamlett** [comment]
Our usage of [MenuBarExtra](https://developer.apple.com/documentation/swiftui/menubarextra/) to provide the system tray icon is only available in MacOS 13+.

**Comment by kkpan11** [comment]
Many models are still stuck in the older version before the `macOS Ventura`.

For the main purpose of **wakatime**(metrics for developers coding stats).
I think it would be better to support as many models as possible.
The newly dropped hardware also includes 2016 products(only 6~7 years). That makes no sense.

Thank you for opening this issue.

---

# Newly dropped hardware
Ventura's release dropped a large amount of Intel hardware, thus requiring the usage of OpenCore Legacy Patcher on the following models (in addition to previously removed models):

- iMac16,1 (21.5-inch, Late 2015)
- iMac16,2 (21.5-inch 4K, Late 2015)
- iMac17,1 (27-inch 5K, Late 2015)
- MacBook9,1 (12-inch, Early 2016)
- MacBookAir7,1 (11-inch, Early 2015)
- MacBookAir7,2 (13-inch, Early 2015)
- MacBookPro11,4 (15-inch, Mid 2015, iGPU)
- MacBookPro11,5 (15-inch, Mid 2015, dGPU)
- MacBookPro12,1 (13-inch, Early 2015)
- MacBookPro13,1 (13-inch, Late 2016)
- MacBookPro13,2 (13-inch, Late 2016)
- MacBookPro13,3 (15-inch, Late 2016)
- Macmini7,1 (Late 2014)
- MacPro6,1 (Late 2013)

References:
https://support.apple.com/en-us/HT213264
https://www.macrumors.com/2022/06/06/macos-ventura-compatibility/
https://dortania.github.io/OpenCore-Legacy-Patcher/VENTURA-DROP.htm

**Comment by alanhamlett** [comment]
We have a dependency on Go, so the oldest MacOS version we support is the one supported by Go. Currently that's `10.14 Mojave` but soon it will be `macOS 10.15 Catalina` when we upgrade wakatime-cli to Go 1.12.

[Go 1.21 will require macOS 10.15 Catalina or later.](https://tip.golang.org/doc/go1.20#darwin)

**Comment by alanhamlett** [comment]
Support for Mac OS 10.15 and newer added with #73 and released in v0.6.1.
