### ISSUE TITLE
Auto update gentle reminder notifications not working

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/macos-wakatime#131]
Was implemented with #119 but after testing it's not showing updates even with an update available. Waited 2 weeks with the app running in system tray and no update notification.

**Comment by gandarez** [comment]
I forced checking for updates
![Screenshot 2023-08-07 at 16 44 48](https://github.com/wakatime/macos-wakatime/assets/782854/a8df9b25-e631-4b03-84ea-55e8ceecc4a7)

**Comment by alanhamlett** [comment]
That's a different error... probably we won't fix that one.

**Comment by alanhamlett** [comment]
Fixed in v3.0.4
