### ISSUE TITLE
Support tracking more apps beyond Xcode

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/macos-wakatime#15]
* default on for all apps
* ability to toggle tracking off per app in settings menu
* start with Figma Desktop or Postman just to get it working for one app, can add more later

**Comment by livid** [comment]
I was thinking about the same when I read the announcement blog.

I am building a native macOS app for publishing blogs with decentralized technologies and would love to add time tracking via this method.

https://www.planetable.xyz/

**Comment by AlfinIndrawan** [comment]
so a question... when will this begin to develop. excited to wait this feature since figma and postman is one of the most used apps developer use!👌
