### ISSUE TITLE
Change figma tracking results from others to figma

### ISSUE THREAD

**Issue by AlfinIndrawan** [wakatime/macos-wakatime#156]
Figma successfully tracked but it seems it was saved as "others" not as "Figma". i want to change it with rules but i cant generalize the activity like the screenshoot. 
<img width="924" alt="Screenshot 2023-08-14 at 11 31 46" src="https://github.com/wakatime/macos-wakatime/assets/77723289/46912389-e62a-4171-b2ae-d74a495068cc">

**Comment by alanhamlett** [comment]
Fixed with #157.
