### ISSUE TITLE
Add iterm or terminal app? (suggesstion)

### ISSUE THREAD

**Issue by AlfinIndrawan** [wakatime/macos-wakatime#158]
i see terminal tracking out there in Wakatime, but it seems a lot of problems such as vs code are not tracked when I use terminal, dont give much better coding stats and so on. 

how about adding iTerm and terminal tracking in wakatime macOS?

**Comment by alanhamlett** [comment]
Iterm2 and Terminal app don't work with Apple's Accessibility APIs, so we can't detect when you're using those applications.
