### ISSUE TITLE
Cannot read properties of undefined (reading 'compiler') #121

### ISSUE THREAD

**Issue by devmdeniz** [wakatime/macos-wakatime#171]
I encountered this error while running ``yarn.cmd run build``.

I am waiting for you to get back to me as I cannot predict what extra information you may request.

<br><br>

![image](https://github.com/wakatime/desktop/assets/68655812/e7d9f10e-7699-47cc-b838-d5fa5ab8f297)

<br><br>
[Duplicate Of](https://github.com/wakatime/desktop/issues/121)

**Comment by alanhamlett** [comment]
That's not this repo.

**Comment by alanhamlett** [comment]
What I meant in wakatime/desktop#121 was to *use* this app if you're using Mac, not to open an issue here. That other repo is an un-finished project. This repo is a different project so that bug isn't related to this repo.

**Comment by devmdeniz** [comment]
> What I meant in [wakatime/desktop#121](https://github.com/wakatime/desktop/issues/121) was to _use_ this app if you're using Mac, not to open an issue here. That other repo is an un-finished project. This repo is a different project so that bug isn't related to this repo.

I apologize for not understanding. I tried to adjust it quickly in a busy moment. I apologize again.

**Comment by alanhamlett** [comment]
Got it, no harm done. I hope we can get that other repo finished in the future.
