### ISSUE TITLE
[Suggestion] Notify user when a new app is added, and prompt them to enable it

### ISSUE THREAD

**Issue by nearlystardust** [wakatime/macos-wakatime#189]
In the current implementation of this app, the app does not notify the user of newly supported apps (in my experience) and auto-enables the app. I recently saw all of my browser activity reported to WakaTime, which I didn't want. In my opinion, this probably shouldn't be auto-enabled -- not everyone wants to track _all_ of their browsing activity here.

**Comment by alanhamlett** [comment]
We tried to notify when new apps are supported in #182, but it's not working so I just disabled tracking all new apps by default in #190.
