### ISSUE TITLE
Support for TablePlus, Terminal, iTerm2

### ISSUE THREAD

**Issue by mikebronner** [wakatime/macos-wakatime#194]
Great idea, would love to see support for the following apps:

- TablePlus
- Terminal (native Mac)

**Comment by icanc0** [comment]
I second this, warp is too heavy for a terminal

**Comment by alanhamlett** [comment]
Added `iTerm2` with #200 and `Terminal` with #201.

For `TablePlus`, what's the `bundleId` for that app?

**Comment by mikebronner** [comment]
@alanhamlett I got the following for the Setapp version of TablePlus:

```
╰─❯ codesign -dr - /Applications/Setapp/TablePlus.app
Executable=/Applications/Setapp/TablePlus.app/Contents/MacOS/TablePlus
designated => anchor apple generic and identifier "com.tinyapp.TablePlus-setapp" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "3X57WP8E8V")
```

**Comment by alanhamlett** [comment]
Added support in [v5.4.0](https://github.com/wakatime/macos-wakatime/releases/tag/v5.4.0).
