### ISSUE TITLE
Support new app: Notion and Apple Notes

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/macos-wakatime#205]
### BundleId of the apps

* `notion.id`
* `com.apple.Notes`

**Comment by wtao901231** [comment]
By the way, bundleId of `WeChat work`

- `com.tencent.WeWorkMac`

Thanks :)

**Comment by brianfromm** [comment]
@alanhamlett It appears that Notion is already supported by Perspect. Are you seeing something different?

<img width="434" alt="Screenshot 2024-02-22 at 11 49 30 AM" src="https://github.com/wakatime/macos-wakatime/assets/69060375/93e76707-d6a6-4205-82aa-1dafac2f7ded">

**Comment by alanhamlett** [comment]
It's in the list, but it's not currently tracked. I don't know how to listen for events when Notion is being used, can currently only detect when Notion gains focus but not if it's actively being used. Also would be great to detect the active workspace and page.
