### ISSUE TITLE
Tracking not working

### ISSUE THREAD

**Issue by charlieforward9** [wakatime/macos-wakatime#219]
I installed the plugin and have it in my Applications folder both in my `MacitoshHD/` path and at my `Users/crich/Applications/` path. I see the icon in my iOS toolbar (twice), and the API key is set. Why am I experiencing this isse? It does not show XCode. I downloaded it from the Mac App Store.

**Comment by alanhamlett** [comment]
You should only run one instance of the app. Delete those two, then download the latest version from the releases page and copy it to your applications folder by unzipping and dragging into the sidebar of a finder window. After running, make sure Xcode is enabled for tracking in the `Monitored apps` menu.

**Comment by charlieforward9** [comment]
@alanhamlett please elaborate on this 

> dragging into the sidebar of a finder window

What should the path of the application be?

**Comment by alanhamlett** [comment]
It actually doesn't matter, you can run it from anywhere. The convention is putting apps in the Applications folder.

**Comment by alanhamlett** [comment]
> It does not show XCode.

Where does it not show Xcode? The Monitored Apps menu or your WakaTime dashboard?

**Comment by charlieforward9** [comment]
It shows on Monitored Apps, not on the WakaTime dashboard.

**Comment by alanhamlett** [comment]
Want to schedule a Zoom call where I can help debug it?

**Comment by charlieforward9** [comment]
Yes please I really appreciate it @alanhamlett 

I am available at any point after 5PM EST. 
Friday the 15th I am availbe all morning.

**Comment by alanhamlett** [comment]
How about Tuesday 5:30pm EST?

**Comment by charlieforward9** [comment]
@alanhamlett works for me. Thank you!

**Comment by charlieforward9** [comment]
@alanhamlett sorry, just checked calendar and remembered I have a 5:30 on Tuesday. What else works for you?

**Comment by alanhamlett** [comment]
How about Wed 5:30pm?

**Comment by charlieforward9** [comment]
@alanhamlett Sorry for the back and forth here... Could we do Thursday 5~5:30?

**Comment by alanhamlett** [comment]
Yes, Thurs 5pm works. I'll send the Zoom link to your email.

**Comment by charlieforward9** [comment]
Thanks for your time Alan.

**Comment by alanhamlett** [comment]
We figured it out over Zoom. It was a bug that we recently fixed in #216 and released in v5.5.5, where you have to re-toggle on Xcode in the `Monitored Apps` menu because toggling Xcode on didn't actually save the setting in an older release.
