### ISSUE TITLE
AppIcon not optimized for Retina Display

### ISSUE THREAD

**Issue by livid** [wakatime/macos-wakatime#25]
System tray icon is low quality.

<img width="41" alt="Screenshot 2023-03-26 at 2 01 13 AM" src="https://user-images.githubusercontent.com/11427/227765728-6898e09c-54e9-4684-a2ab-30498d4da198.png">

**Comment by alanhamlett** [comment]
Yea, I tried fixing that but could only get it to use the low-res AppIcon.

**Comment by livid** [comment]
I tested a way, and it worked! If you turn the WakaTime image into an SF Symbol and import it as Symbol Image Set, then it will display properly.

Here I used an asset from my project for testing.

<img width="124" alt="Screenshot 2023-03-26 at 6 47 13 AM" src="https://user-images.githubusercontent.com/11427/227780095-16fccf87-8c1c-49c2-b72e-c9e4bea85d58.png">

**Comment by ChesterYue** [comment]
#26

**Comment by alanhamlett** [comment]
Released in v0.1.0 just now:
https://github.com/wakatime/macos-wakatime/releases/tag/v0.1.0-alpha.1
