### ISSUE TITLE
Support new app: Affinity {Designer,Photo,Publisher}

### ISSUE THREAD

**Issue by christippett** [wakatime/macos-wakatime#259]
### BundleId of the app

com.seriflabs.affinitydesigner2
com.seriflabs.affinityphoto2
com.seriflabs.affinitypublisher2

### Example window titles

Title follows the scheme:
{Application Name} - {Document Name} [Modified] ({Zoom %})

Examples:
Affinity Designer 2 - <Untitled> (130.5%)
Affinity Designer 2 - Awesome Design [Modified] (20.5%)
Affinity Photo 2 - IMG_591 (10.5%)
Affinity Publisher 2 - My Book [Modified] (120%)

**Comment by alanhamlett** [comment]
Implemented with #297.
