### ISSUE TITLE
Support new app: Arc Browser

### ISSUE THREAD

**Issue by vitaliano-fortis** [wakatime/macos-wakatime#281]
### BundleId of the app

company.thebrowser.Browser

### Example window titles

gmail
GitHub
Google

**Comment by alanhamlett** [comment]
We already support ArcBrowser, unless it's broken?

https://github.com/wakatime/macos-wakatime/blob/main/WakaTime/Watchers/MonitoredApp.swift#L4

**Comment by Josyann** [comment]
Hey @alanhamlett I think it's broken! 😬 
On the dashboard I can see warp or slack for example, but not arc.
App is up to date: 5.23.1

There's no errors in these logs:
```
#  ~/.wakatime/macos-wakatime.log

2024-08-30 09:16:16.924: App changed from Arc to Warp (dev.warp.Warp-Stable)
2024-08-30 09:16:33.522: App changed from Warp to RubyMine (com.jetbrains.rubymine)
2024-08-30 09:16:34.281: App changed from RubyMine to Warp (dev.warp.Warp-Stable)
2024-08-30 09:16:36.205: App changed from Warp to RubyMine (com.jetbrains.rubymine)
2024-08-30 09:16:39.633: App changed from RubyMine to Arc (company.thebrowser.Browser)
2024-08-30 09:16:42.634: App changed from Arc to Warp (dev.warp.Warp-Stable)

#  ~/.wakatime/wakatime.log
# Errors from a few days ago fixed by a reinstall.

{"caller":"pkg/language/chroma.go:127","file":"README.md","func":"language.selectByCustomizedPriority","level":"warning","message":"failed to load folder files extensions: failed to read directory: open : no such file or directory","now":"2024-08-26T18:49:37+02:00","os/arch":"darwin/arm64","plugin":"Warp/0.1.0-20240814.223322 macos-wakatime/5.20.0","time":1724690977.517945,"version":"v1.98.3"}
{"caller":"pkg/language/chroma.go:132","file":"README.md","func":"language.selectByCustomizedPriority","level":"warning","message":"failed to load head from file \"README.md\": failed to open file: open README.md: no such file or directory","now":"2024-08-26T18:49:37+02:00","os/arch":"darwin/arm64","plugin":"Warp/0.1.0-20240814.223322 macos-wakatime/5.20.0","time":1724690977.517945,"version":"v1.98.3"}
```

Is there anything I can do on my side? Thanks!

**Comment by qmkCamel** [comment]
I have the same problem. There are Arc logs in macos-wakatime.log, but cann`t see Arc in the dashboard.

**Comment by qmkCamel** [comment]
@Josyann Hi, does your Arc track works now?

**Comment by qmkCamel** [comment]
@alanhamlett 
Found  the problem. The function  https://github.com/wakatime/macos-wakatime/blob/0e3a21ad9dfb9d4f2e2333d87921c964f982bce2/WakaTime/Helpers/MonitoringManager.swift#L459 missed the `.arcbrowser`  support.
I try to mock the address and it can track the Arc as expected.


> We already support ArcBrowser, unless it's broken?
> 
> [macos-wakatime/WakaTime/Watchers/MonitoredApp.swift](https://github.com/wakatime/macos-wakatime/blob/69cc88ee443d49b160cdeabbbff65041741e0321/WakaTime/Watchers/MonitoredApp.swift#L4)
> 
> Line 4 in [69cc88e](/wakatime/macos-wakatime/commit/69cc88ee443d49b160cdeabbbff65041741e0321)
> 
>  case arcbrowser = "company.thebrowser.Browser"

**Comment by Josyann** [comment]
@qmkCamel Nope, still not working, good catch!
@alanhamlett I think this is it 😌

**Comment by alanhamlett** [comment]
How about with the latest version, v5.26.3?

**Comment by qmkCamel** [comment]
> How about with the latest version, v5.26.3?

Great, it works as expected @alanhamlett

**Comment by darrinholst** [comment]
worth noting that you have to have developer mode turned on for the domains you want to track so Arc shows the url bar
