### ISSUE TITLE
Support new app: Zed

### ISSUE THREAD

**Issue by labithiotis** [wakatime/macos-wakatime#282]
### BundleId of the app

dev.zed.Zed

### Example window titles

Zed

**Comment by alexreyes** [comment]
I would really like Zed support as well. I saw this issue: https://github.com/zed-industries/extensions/issues/497 and I was wondering if just adding support for the bundle ID would be enough to get the tracking working. Happy to make the PR if this would work

**Comment by labithiotis** [comment]
> I would really like Zed support as well. I saw this issue: https://github.com/zed-industries/extensions/issues/497 and I was wondering if just adding support for the bundle ID would be enough to get the tracking working. Happy to make the PR if this would work

That was my initial thought too but honestly wouldn't have a clue if my changes were correct, I would only be following previous PRs to add new test cases. If your more confident and happy to make a PR that would be awesome 🤩

**Comment by alanhamlett** [comment]
I'm working on adding zed support to the Mac desktop app this week.

**Comment by alexreyes** [comment]
Amazing, super excited for it! @alanhamlett

**Comment by labithiotis** [comment]
@alanhamlett when will the version with Zed support be released?

**Comment by alanhamlett** [comment]
I was waiting to see if we can detect the absolute file path instead of just the file name, to detect programming language from the file. I haven't found a way so I'll just release as-is.

**Comment by bestgopher** [comment]
@labithiotis I published a plugin for [zed](https://github.com/bestgopher/wakatime-zed), you may try it. You could install it by search wakatime in extension page.

**Comment by labithiotis** [comment]
@bestgopher Nice, that also works as well as waka desktop app. Good job 👍🏻
