### ISSUE TITLE
App crash when switching project in Xcode

### ISSUE THREAD

**Issue by SeNeO** [wakatime/macos-wakatime#29]
I'm glad to see wakatime for xcode back.

But I have an issue, the application seems to crash whenever I switch to another xcode window with a different project open in it. I didn't have this issue when compiling/running the application from xcode. But I had this issue when I moved the executable to my Application folder, and now I have the same issue with the release downloaded.

Is there anyone else that have the same issue?

**Comment by alanhamlett** [comment]
Does the file you're editing contain a space in it's path? Might be a duplicate of #27.

**Comment by SeNeO** [comment]
Indeed. I read this issue to quickly, I should've made the connection.
